name: run
on:
  push:
    branches:
    - master
  schedule:
    - cron: '15 11 28 * *' # Every Day at 4PM NST (10:15am UTC)
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: Execute Scraping Script
        run: |
          python mutual_funds.py
          
      - name: Commit and Push Files
        run: |
           git config --local user.email "madhuko@outlook.com"
           git config --local user.name "madhuko"        
           git add .
           git commit -m "Operation Completed successfully" -a
           git push origin main
